### PR TITLE
Fix rainbow-delimiters

### PR DESCRIPTION
**Pull request by drot**
Inheritance from outline-mode doesn't work for some reason (colors are not applied at all), so I adjusted the colors a bit.

### CODE REVIEW

**Comment by wasamasa** [comment]
Um, how did you enable the theme?  Did you disable the previously active theme as well?

**Comment by drot** [comment]
Tested with a blank init, added the MELPA repository and installed `rainbow-delimiters` and `gotham-theme`. Loaded the theme with `M-x load-theme` and ran `M-x rainbow-delimiters-mode` and no colors were applied. Regardless of this I wanted to swap the colors around a bit for more visibility.

**Comment by wasamasa** [comment]
Well, this is interesting.  If I repro it as you've described, `M-x describe-face` refuses to work with `outline-1` and such, but loading up `outline.el` makes them take up the expected color.  That is certainly fascinating, I don't remember this behavior in older Emacs versions and suspect a bug.

**Comment by drot** [comment]
Was reported here too: Fanael/rainbow-delimiters#21 The Solarized theme mentioned there also uses inheritance from `outline-mode` faces.

**Comment by wasamasa** [comment]
Yeah, that's where I got the idea from.  I hope I won't have to undo that, so I'll investigate on debbugs.

**Comment by drot** [comment]
Ok, but can this still be merged or you do not agree with the swapped colors?

**Comment by wasamasa** [comment]
My issue with merging this is that the issue still remains with all other definitions inheriting from `outline.el` faces.

**Comment by wasamasa** [comment]
I've checked debbugs and found a thread where Stefan wrote that we're relying too much on `:inherit` specs.  It's OK if you're inheriting from a face that's loaded up, which allows for both core definitions (in `faces.el`) and other faces in the same package.  Depending on faces from a different package is a no-go, so I fixed all those cases and incorporated your changes.

**Comment by drot** [comment]
Thanks for the info!

**Pull request closed without merging**
