### PR TITLE
support for w3m-browser

### PR DESCRIPTION
**Pull request by nullx002**

### CODE REVIEW

**Comment by wasamasa** [comment]
Thanks!  This looks like a good base, however some face definitions are still missing:

- w3m-form-button
- w3m-form-button-mouse
- w3m-form-button-pressed
- w3m-form-inactive
- w3m-insert
- w3m-error

Do you plan to add these?

**Comment by nullx002** [comment]
ok, i will add those and will commit and inform you. thanks!!

**Comment by nullx002** [comment]
added missing definitions, it worked for me. please check. thanks.

**Comment by wasamasa** [comment]
- `w3m-bold` is practically invisible, please remove the foreground color
- There's trailing whitespace and double spaces between arguments
- What's the deal with the two rather unclear comments?  One of the goals of the theme is that semantically equivalent faces should look the same, so if links in w3m look like in gnus, that's a good thing, no?  Or am I missing something here?

**Comment by nullx002** [comment]
thanks for the reply, your 1st and 3rd comment is related to my personal customization so will remove them. sorry, that i forgot while copying code to repo. will remove white spaces and update it here.
thanks again.

**Comment by nullx002** [comment]
comments were related to me having a problem with underlines in gnus, removed. it was my personal customization. whitespace was just me being lazy. updated code. please check.

**Comment by nullx002** [comment]
Vasilij Schneidermann <notifications@github.com> writes:

>   * w3m-bold is practically invisible, please remove the foreground color
>   * There's trailing whitespace and double spaces between arguments
>   * What's the deal with the two rather unclear comments? One of the goals of the theme is that semantically equivalent faces should look the same, so if links in w3m look
>     like in gnus, that's a good thing, no? Or am I missing something here?
>

updated PR please check

-- 
~nullx002 (somewhere on pale blue dot)
github.com/nullx002
bitbucket.org/nullx002
twitter.com/nullx002

**Comment by wasamasa** [comment]
You're getting closer.

- Trailing whitespace in the last line (924)
- `w3m-header-line-location-content` is hard to read, please replace it with `base4`

**Pull request merged**
