### PR TITLE
mu4e: set header-related faces

### PR DESCRIPTION
**Pull request by jinnovation**

### CODE REVIEW

**Comment by wasamasa** [comment]
Hmm, doesn't mu4e have more faces?

**Comment by jinnovation** [comment]
It does, but the rest of them seem to inherit face attributes that blend in very well with the rest of the theme. The two additions I've made here address the more egregious deviations. `mu4e-header-key-face`, for instance, was a very incongruous shade of bright green originally, which this patch addresses.

Do you suggest coding up the rest of the faces?

**Comment by wasamasa** [comment]
I'll update my local installation of mu4e first and see.

**Comment by wasamasa** [comment]
Nice, looks like the AUR version got finally fixed and yes, most of the faces are set to something meaningful.

I can identify more than `mu4e-header-highlight-face` (which is overdone IMO, just using the region face would suffice) and `mu4e-header-key-face` (which derives from the uncustomized `message-header-name-face`, perhaps theming `message-mode` would be smarter as all the mail clients use it), namely `mu4e-compose-separator-face`, `mu4e-compose-header-face` and `mu4e-region-face` (why is that even a thing?).

**Comment by jinnovation** [comment]
Will look into setting those faces.

For `mu4e-header-highlight-face`, alternatively, how do you feel about having it inherit from the `hl-line` face, to better fit its denoting a "current" item, rather than a "region" per se?

**Comment by wasamasa** [comment]
That sounds even more sensible. A similiar policy could be used for `mu4e-region-face`.

**Comment by jinnovation** [comment]
Made some additions; take a look and see if there's anything I left out or that could be improved?

**Comment by wasamasa** [comment]
`message-mode` comes with more faces than that, but at this point it would make sense to join and split this up to two commits so that both the `mu4e` and `message-mode` changes stand on their own. Feel free to do this with a rebase and force push, alternatively I could build upon your work and add the missing faces myself.

**Comment by wasamasa** [comment]
As there was no further reply, I did add the faces myself in the meantime.

**Comment by jinnovation** [comment]
Apologies for not getting to it. Thanks as always for the work.

**Pull request closed without merging**
